name: first workflow

on: push

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 main.py
    
  dokcker:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola GH Actions"
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build y push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: avic19/holamundo
